/*
 * Armadillo API
 *
 * This is a api spec for Armadillo
 *
 * API version: 0.0.1
 * Contact: holmes89@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

import (
	"encoding/json"
	"net/http"
	"strings"
)

// LoginApiController binds http requests to an api service and writes the service results to the http response
type LoginApiController struct {
	service      LoginApiServicer
	errorHandler ErrorHandler
}

// LoginApiOption for how the controller is set up.
type LoginApiOption func(*LoginApiController)

// WithLoginApiErrorHandler inject ErrorHandler into controller
func WithLoginApiErrorHandler(h ErrorHandler) LoginApiOption {
	return func(c *LoginApiController) {
		c.errorHandler = h
	}
}

// NewLoginApiController creates a default api controller
func NewLoginApiController(s LoginApiServicer, opts ...LoginApiOption) Router {
	controller := &LoginApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the LoginApiController
func (c *LoginApiController) Routes() Routes {
	return Routes{
		{
			"Authenticate",
			strings.ToUpper("Post"),
			"/v1/armadillo/login",
			c.Authenticate,
		},
	}
}

// Authenticate -
func (c *LoginApiController) Authenticate(w http.ResponseWriter, r *http.Request) {
	loginParam := Login{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&loginParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertLoginRequired(loginParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Authenticate(r.Context(), loginParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
