/*
 * Armadillo API
 *
 * This is a api spec for Armadillo
 *
 * API version: 0.0.1
 * Contact: holmes89@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// ImplResponse response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
