/*
 * Armadillo API
 *
 * This is a api spec for Armadillo
 *
 * API version: 0.0.1
 * Contact: holmes89@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

type Authentication struct {

	RefreshToken string `json:"refresh_token,omitempty"`

	Token string `json:"token,omitempty"`

	Session string `json:"session,omitempty"`
}

// AssertAuthenticationRequired checks if the required fields are not zero-ed
func AssertAuthenticationRequired(obj Authentication) error {
	return nil
}

// AssertRecurseAuthenticationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Authentication (e.g. [][]Authentication), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAuthenticationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAuthentication, ok := obj.(Authentication)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAuthenticationRequired(aAuthentication)
	})
}
