/*
 * Armadillo API
 *
 * This is a api spec for Armadillo
 *
 * API version: 0.0.1
 * Contact: holmes89@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

type Login struct {

	RefreshToken string `json:"refresh_token,omitempty"`

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`

	Session string `json:"session,omitempty"`
}

// AssertLoginRequired checks if the required fields are not zero-ed
func AssertLoginRequired(obj Login) error {
	return nil
}

// AssertRecurseLoginRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Login (e.g. [][]Login), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLoginRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLogin, ok := obj.(Login)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLoginRequired(aLogin)
	})
}
